# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - openstack-ansible-role-jobs
      - check-requirements
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - openstack-ansible-upgrade-ubuntu-xenial
        - openstack-ansible-lxd-ubuntu-xenial
        - openstack-ansible-nova-ssl-nv
        # TODO(jrosser) Revert this once bionic passes
        - openstack-ansible-functional-ubuntu-bionic:
            voting: false
        - openstack-ansible-functional-distro_install-centos-7
        - openstack-ansible-functional-distro_install-opensuse-423
        # NOTE(hwoarang) xenial does not currently work. It needs investigation
        - openstack-ansible-functional-distro_install-ubuntu-xenial:
            voting: false
    gate:
      jobs:
        - openstack-ansible-upgrade-ubuntu-xenial
        - openstack-ansible-lxd-ubuntu-xenial
        # TODO(jrosser) Revert this once bionic passes
        - openstack-ansible-functional-ubuntu-bionic:
            voting: false
        - openstack-ansible-functional-distro_install-centos-7
        - openstack-ansible-functional-distro_install-opensuse-423
